const PDFDocument = require("pdfkit");

const generatePDF = (project, res) => {
  const { idea, blueprint } = project;

  const doc = new PDFDocument({
    margin: 50,
    size: "A4"
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${idea.replace(/\s+/g, "-")}.pdf`
  );

  doc.pipe(res);

  // ===== TITLE =====
  doc
    .fontSize(22)
    .font("Helvetica-Bold")
    .text(idea, { align: "center" });

  doc.moveDown(2);

  // ===== FEATURES =====
  doc
    .fontSize(16)
    .font("Helvetica-Bold")
    .text("Features (MVP)");

  doc.moveDown(0.5);
  doc.fontSize(12).font("Helvetica");

  blueprint.features.mvp.forEach(feature => {
    doc.text(`• ${feature}`);
  });

  doc.moveDown(2);

  // ===== TECH STACK =====
  doc
    .fontSize(16)
    .font("Helvetica-Bold")
    .text("Tech Stack");

  doc.moveDown(0.5);
  doc.fontSize(12).font("Helvetica");

  doc.text(`Frontend: ${blueprint.techStack.frontend}`);
  doc.text(`Backend: ${blueprint.techStack.backend}`);
  doc.text(`Database: ${blueprint.techStack.database}`);
  doc.text(`Auth: ${blueprint.techStack.auth}`);

  doc.moveDown(2);

  // ===== DATABASE =====
  doc
    .fontSize(16)
    .font("Helvetica-Bold")
    .text("Database Collections");

  doc.moveDown(0.5);
  doc.fontSize(12).font("Helvetica");

  blueprint.database.collections.forEach(collection => {
    doc.text(`• ${collection}`);
  });

  doc.moveDown(2);

  // ===== FOOTER =====
  doc
    .fontSize(10)
    .fillColor("gray")
    .text(
      `Generated by BuildScope on ${new Date().toLocaleDateString()}`,
      { align: "center" }
    );

  doc.end();
};

module.exports = generatePDF;
